"""version: 1.2.0
description: Domain enum definitions, subscription statuses, and feature flags.
updated: 2026-05-17
"""

from enum import StrEnum


class Marketplace(StrEnum):
    WB = "WB"
    OZON = "OZON"


class AccountStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ERROR = "ERROR"
    DISABLED = "DISABLED"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"


class SaleModel(StrEnum):
    FBS = "FBS"
    FBO = "FBO"
    RFBS = "rFBS"
    DBS = "DBS"
    DBW = "DBW"


class UrgencyType(StrEnum):
    ACTION_REQUIRED = "ACTION_REQUIRED"
    INFORMATIONAL = "INFORMATIONAL"


class SourceEventType(StrEnum):
    LIVE_ORDER = "LIVE_ORDER"
    STATISTICS_ORDER = "STATISTICS_ORDER"
    REPORT_ORDER = "REPORT_ORDER"
    POSTING_EVENT = "POSTING_EVENT"


class FboNotificationMode(StrEnum):
    INSTANT = "INSTANT"
    DIGEST_30_MIN = "DIGEST_30_MIN"
    DAILY_ONLY = "DAILY_ONLY"


class CalculationType(StrEnum):
    ESTIMATED = "ESTIMATED"
    ACTUAL = "ACTUAL"


class EconomyConfidence(StrEnum):
    EXACT = "EXACT"
    ESTIMATED = "ESTIMATED"
    PRELIMINARY = "PRELIMINARY"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class ReconciliationStatus(StrEnum):
    PRELIMINARY = "PRELIMINARY"
    FACT_MATCHED = "FACT_MATCHED"
    FACT_PARTIAL = "FACT_PARTIAL"
    FACT_UNMATCHED = "FACT_UNMATCHED"
    FACT_AMBIGUOUS = "FACT_AMBIGUOUS"
    FACT_CONFLICT = "FACT_CONFLICT"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ExpenseSource(StrEnum):
    FINANCIAL_REPORT = "FINANCIAL_REPORT"
    WB_TARIFF_API = "WB_TARIFF_API"
    WB_LOGISTICS_TARIFF_API = "WB_LOGISTICS_TARIFF_API"
    OZON_TARIFF_DB = "OZON_TARIFF_DB"
    OZON_FINANCIAL_DATA = "OZON_FINANCIAL_DATA"
    FALLBACK_DEFAULT = "FALLBACK_DEFAULT"
    UNKNOWN = "UNKNOWN"


class FeatureCode(StrEnum):
    WEB_DASHBOARD = "web_dashboard"
    ADVANCED_ANALYTICS = "advanced_analytics"
    PLAN_FACT = "PLAN_FACT"
    BREAK_EVEN = "break_even"
    MASTER_PRODUCT_ANALYTICS = "MASTER_PRODUCT_ANALYTICS"
    STOCKOUT_FORECAST = "STOCKOUT_FORECAST"
    STOCK_FORECAST = "stock_forecast"
    DATA_QUALITY = "DATA_QUALITY"
    EXPORTS = "EXPORTS"
    AI_ANALYST = "AI_ANALYST"
    MULTI_ACCOUNT = "MULTI_ACCOUNT"
    LONG_HISTORY = "LONG_HISTORY"
    ALERTS = "alerts"
    API_ACCESS = "api_access"
    AUTO_PROMOTIONS = "auto_promotions"
    MRC_PRICING = "MRC_PRICING"
    PRICE_MANAGEMENT = "price_management"


class AlertType(StrEnum):
    LOSS_ORDER = "LOSS_ORDER"
    LOW_MARGIN = "LOW_MARGIN"
    MISSING_COST = "MISSING_COST"
    LOW_STOCK = "LOW_STOCK"
    STOCKOUT_FORECAST = "STOCKOUT_FORECAST"
    FBS_DEADLINE_RISK = "FBS_DEADLINE_RISK"
    LOGISTICS_GROWTH = "LOGISTICS_GROWTH"
    BUYOUT_DROP = "BUYOUT_DROP"
    ORDERS_DROP = "ORDERS_DROP"


class NotificationType(StrEnum):
    NEW_ORDER = "NEW_ORDER"
    ORDER_FBS = "ORDER_FBS"
    ORDER_RFBS = "ORDER_RFBS"
    ORDER_FBO = "ORDER_FBO"
    FBO_DIGEST = "FBO_DIGEST"
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_DIGEST = "SALE_DIGEST"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    RETURN_CREATED = "RETURN_CREATED"
    DAILY_REPORT = "DAILY_REPORT"
    FBS_CONTROL = "FBS_CONTROL"
    STOCK_ALERT = "STOCK_ALERT"
    PROFIT_ALERT = "PROFIT_ALERT"


class SyncJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SyncJobType(StrEnum):
    INITIAL_HISTORY_BACKFILL = "INITIAL_HISTORY_BACKFILL"
    MANUAL_HISTORY_BACKFILL = "MANUAL_HISTORY_BACKFILL"
    FINANCIAL_HISTORY_BACKFILL = "FINANCIAL_HISTORY_BACKFILL"


class SaleEventType(StrEnum):
    BUYOUT = "BUYOUT"
    SALE_COMPLETED = "SALE_COMPLETED"
    DELIVERED_TO_CUSTOMER = "DELIVERED_TO_CUSTOMER"


class SubscriptionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REPLACED = "REPLACED"
    TRIAL = "TRIAL"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class PromoType(StrEnum):
    PERCENT_DISCOUNT = "percent_discount"
    FIXED_DISCOUNT = "fixed_discount"
    FREE_DAYS = "free_days"


class PromoUsageStatus(StrEnum):
    RESERVED = "reserved"
    APPLIED = "applied"
    CANCELLED = "cancelled"
