"""version: 1.0.0
description: Domain enum definitions.
updated: 2026-05-14
"""

from enum import StrEnum


class Marketplace(StrEnum):
    WB = "WB"
    OZON = "OZON"


class AccountStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ERROR = "ERROR"
    DISABLED = "DISABLED"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"


class SaleModel(StrEnum):
    FBS = "FBS"
    FBO = "FBO"
    RFBS = "rFBS"
    DBS = "DBS"
    DBW = "DBW"


class UrgencyType(StrEnum):
    ACTION_REQUIRED = "ACTION_REQUIRED"
    INFORMATIONAL = "INFORMATIONAL"


class SourceEventType(StrEnum):
    LIVE_ORDER = "LIVE_ORDER"
    STATISTICS_ORDER = "STATISTICS_ORDER"
    REPORT_ORDER = "REPORT_ORDER"
    POSTING_EVENT = "POSTING_EVENT"


class FboNotificationMode(StrEnum):
    INSTANT = "INSTANT"
    DIGEST_30_MIN = "DIGEST_30_MIN"
    DAILY_ONLY = "DAILY_ONLY"


class CalculationType(StrEnum):
    ESTIMATED = "ESTIMATED"
    ACTUAL = "ACTUAL"


class AlertType(StrEnum):
    LOSS_ORDER = "LOSS_ORDER"
    LOW_MARGIN = "LOW_MARGIN"
    MISSING_COST = "MISSING_COST"
    LOW_STOCK = "LOW_STOCK"
    STOCKOUT_FORECAST = "STOCKOUT_FORECAST"
    FBS_DEADLINE_RISK = "FBS_DEADLINE_RISK"
    LOGISTICS_GROWTH = "LOGISTICS_GROWTH"
    BUYOUT_DROP = "BUYOUT_DROP"
    ORDERS_DROP = "ORDERS_DROP"


class NotificationType(StrEnum):
    NEW_ORDER = "NEW_ORDER"
    ORDER_FBS = "ORDER_FBS"
    ORDER_RFBS = "ORDER_RFBS"
    ORDER_FBO = "ORDER_FBO"
    FBO_DIGEST = "FBO_DIGEST"
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_DIGEST = "SALE_DIGEST"
    DAILY_REPORT = "DAILY_REPORT"
    FBS_CONTROL = "FBS_CONTROL"
    STOCK_ALERT = "STOCK_ALERT"
    PROFIT_ALERT = "PROFIT_ALERT"


class SyncJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SyncJobType(StrEnum):
    INITIAL_HISTORY_BACKFILL = "INITIAL_HISTORY_BACKFILL"
    MANUAL_HISTORY_BACKFILL = "MANUAL_HISTORY_BACKFILL"
    FINANCIAL_HISTORY_BACKFILL = "FINANCIAL_HISTORY_BACKFILL"


class SaleEventType(StrEnum):
    BUYOUT = "BUYOUT"
    SALE_COMPLETED = "SALE_COMPLETED"
    DELIVERED_TO_CUSTOMER = "DELIVERED_TO_CUSTOMER"
